### ISSUE TITLE
webui.call not working

### ISSUE THREAD

**Issue by cesarjimoc** [webui-dev/python-webui#3]
webui.call while executing python on javascript not working a had to use webui_fn to make it work it says something like webui not defined ...

**Comment by hassandraga** [comment]
Everything is up-to-date now.

![image](https://github.com/webui-dev/python-webui/assets/16948659/b1518797-c453-48e6-8523-371209492334)

**Comment by cesarjimoc** [comment]
Thanks 👍

**Comment by hassandraga** [comment]
Now PyPI package _v2.4.0._**1** supports ARM64.

`pip install --upgrade webui2`
